/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/dzsb-002295/Desktop/JY/other/cube-doc/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-8a2871de",
    path: "/guide/main.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8a2871de").then(next)
    },
  },
  {
    name: "v-c10530c4",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c10530c4").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-79cfeb9d",
    path: "/official/main.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-79cfeb9d").then(next)
    },
  },
  {
    name: "v-3b14cc5a",
    path: "/develop/main.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b14cc5a").then(next)
    },
  },
  {
    name: "v-50cdc49d",
    path: "/assemb/main.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-50cdc49d").then(next)
    },
  },
  {
    name: "v-9d74be46",
    path: "/panorama/main.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9d74be46").then(next)
    },
  },
  {
    name: "v-6e9db5f7",
    path: "/product/main.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e9db5f7").then(next)
    },
  },
  {
    name: "v-17a66c9d",
    path: "/platform/main.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-17a66c9d").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]