/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/dz0400878/Desktop/cube-doc/cube-doc/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-7ae0ad08",
    path: "/develop/main.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ae0ad08").then(next)
    },
  },
  {
    name: "v-6bde2112",
    path: "/assemb/main.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6bde2112").then(next)
    },
  },
  {
    name: "v-37e2bcc6",
    path: "/guide/main.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-37e2bcc6").then(next)
    },
  },
  {
    name: "v-b879f4dc",
    path: "/official/main.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b879f4dc").then(next)
    },
  },
  {
    name: "v-1b1ee7ee",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b1ee7ee").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-498e8a5c",
    path: "/panorama/main.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-498e8a5c").then(next)
    },
  },
  {
    name: "v-0708c92c",
    path: "/product/main.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0708c92c").then(next)
    },
  },
  {
    name: "v-41998692",
    path: "/platform/main.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-41998692").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]