/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "魔方低代码",
  "description": "Just playing around",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/assets/logo.png",
        "heroText": "魔方低代码",
        "tagline": "魔方低代码",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-c10530c4",
      "path": "/"
    },
    {
      "title": "快速上手",
      "frontmatter": {},
      "regularPath": "/guide/one.html",
      "relativePath": "guide/one.md",
      "key": "v-bdd00d46",
      "path": "/guide/one.html",
      "headers": [
        {
          "level": 2,
          "title": "如何创建一个项目",
          "slug": "如何创建一个项目"
        },
        {
          "level": 3,
          "title": "新建H5项目",
          "slug": "新建h5项目"
        },
        {
          "level": 3,
          "title": "页面搭建",
          "slug": "页面搭建"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/two.html",
      "relativePath": "guide/two.md",
      "key": "v-01fb8b9d",
      "path": "/guide/two.html"
    }
  ],
  "themeConfig": {
    "logo": "/assets/logo.png",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "指南",
        "link": "/guide/one"
      }
    ],
    "sidebar": [
      "/guide/one",
      [
        "/guide/two",
        "Explicit link text"
      ]
    ]
  }
}