/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "魔方低代码",
  "description": "Just playing around",
  "base": "/cube-doc/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "https://p6.1-xian.cn/bx-user/447a642189404884af861065c7df1c2d.png",
        "heroText": "魔方低代码",
        "tagline": "创意无限，打造复杂营收活动的首选",
        "actionText": "快速上手 →",
        "actionLink": "/platform/main",
        "features": [
          {
            "title": "简单易懂",
            "details": "组件拖拽配置，傻瓜化实现你的营销、营收需求"
          },
          {
            "title": "组件沉淀",
            "details": "支持自定义组件，将团队内长期使用的玩法沉淀输出，同样可以拖拽完成搭建"
          },
          {
            "title": "玩法输出",
            "details": "平台将自身玩法抽象组件，如榜单、任务等数十款，开箱即用，省去业务开发成本"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-c10530c4",
      "path": "/",
      "lastUpdated": "11/28/2023, 8:06:52 PM",
      "lastUpdatedTimestamp": 1701173212000
    },
    {
      "title": "组件开发",
      "frontmatter": {},
      "regularPath": "/develop/main.html",
      "relativePath": "develop/main.md",
      "key": "v-3b14cc5a",
      "path": "/develop/main.html",
      "headers": [
        {
          "level": 2,
          "title": "组件规范",
          "slug": "组件规范"
        },
        {
          "level": 2,
          "title": "编译发布",
          "slug": "编译发布"
        },
        {
          "level": 2,
          "title": "导入平台",
          "slug": "导入平台"
        },
        {
          "level": 2,
          "title": "项目使用",
          "slug": "项目使用"
        }
      ],
      "lastUpdated": "11/28/2023, 8:06:52 PM",
      "lastUpdatedTimestamp": 1701173212000
    },
    {
      "title": "快速上手",
      "frontmatter": {},
      "regularPath": "/guide/main.html",
      "relativePath": "guide/main.md",
      "key": "v-8a2871de",
      "path": "/guide/main.html",
      "headers": [
        {
          "level": 2,
          "title": "如何创建一个项目",
          "slug": "如何创建一个项目"
        },
        {
          "level": 3,
          "title": "新建H5项目",
          "slug": "新建h5项目"
        },
        {
          "level": 3,
          "title": "页面搭建",
          "slug": "页面搭建"
        }
      ],
      "lastUpdated": "11/28/2023, 8:06:52 PM",
      "lastUpdatedTimestamp": 1701173212000
    },
    {
      "title": "官方组件",
      "frontmatter": {},
      "regularPath": "/official/main.html",
      "relativePath": "official/main.md",
      "key": "v-79cfeb9d",
      "path": "/official/main.html",
      "headers": [
        {
          "level": 2,
          "title": "图片",
          "slug": "图片"
        },
        {
          "level": 2,
          "title": "榜单",
          "slug": "榜单"
        },
        {
          "level": 2,
          "title": "任务",
          "slug": "任务"
        }
      ],
      "lastUpdated": "11/28/2023, 8:06:52 PM",
      "lastUpdatedTimestamp": 1701173212000
    },
    {
      "title": "平台概览",
      "frontmatter": {},
      "regularPath": "/platform/main.html",
      "relativePath": "platform/main.md",
      "key": "v-17a66c9d",
      "path": "/platform/main.html",
      "headers": [
        {
          "level": 2,
          "title": "基本介绍",
          "slug": "基本介绍"
        },
        {
          "level": 2,
          "title": "为什么是Cube？",
          "slug": "为什么是cube"
        }
      ],
      "lastUpdated": "11/28/2023, 8:06:52 PM",
      "lastUpdatedTimestamp": 1701173212000
    },
    {
      "title": "一秒看懂Cube",
      "frontmatter": {},
      "regularPath": "/panorama/main.html",
      "relativePath": "panorama/main.md",
      "key": "v-9d74be46",
      "path": "/panorama/main.html",
      "headers": [
        {
          "level": 2,
          "title": "架构图",
          "slug": "架构图"
        },
        {
          "level": 2,
          "title": "时序图",
          "slug": "时序图"
        }
      ],
      "lastUpdated": "11/28/2023, 8:06:52 PM",
      "lastUpdatedTimestamp": 1701173212000
    },
    {
      "title": "产品介绍",
      "frontmatter": {},
      "regularPath": "/product/main.html",
      "relativePath": "product/main.md",
      "key": "v-6e9db5f7",
      "path": "/product/main.html",
      "headers": [
        {
          "level": 2,
          "title": "登陆注册",
          "slug": "登陆注册"
        },
        {
          "level": 2,
          "title": "团队管理",
          "slug": "团队管理"
        },
        {
          "level": 2,
          "title": "组件库管理",
          "slug": "组件库管理"
        }
      ],
      "lastUpdated": "11/28/2023, 8:06:52 PM",
      "lastUpdatedTimestamp": 1701173212000
    }
  ],
  "themeConfig": {
    "search": false,
    "lastUpdated": "Last Updated",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "文档",
        "link": "/platform/main"
      },
      {
        "text": "体验",
        "link": "https://web.bxcube.com/cube/"
      }
    ],
    "sidebar": [
      "/platform/main.md",
      "/panorama/main.md",
      "/product/main.md",
      "/guide/main.md",
      "/official/main.md",
      "/develop/main.md"
    ]
  }
}